#!/bin/sh

ACTION=`zenity --width=90 --height=320 --list --radiolist --text="Select logout action" --title="Logout" --column "Choice" --column "Action" TRUE Shutdown FALSE Reboot FALSE Suspend FALSE Hibernate FALSE LockScreen FALSE Logout 2> /dev/null`

if [ -n "${ACTION}" ];then
    case $ACTION in
        Shutdown)
            zenity --question --text "Are you sure you want to halt?" 2> /dev/null && dbus-send --system --print-reply --dest="org.freedesktop.ConsoleKit" /org/freedesktop/ConsoleKit/Manager org.freedesktop.ConsoleKit.Manager.Stop
            ;;
        Reboot)
            zenity --question --text "Are you sure you want to reboot?" 2> /dev/null && dbus-send --system --print-reply --dest="org.freedesktop.ConsoleKit" /org/freedesktop/ConsoleKit/Manager org.freedesktop.ConsoleKit.Manager.Restart
            ;;
        Suspend)
            dbus-send --system --print-reply --dest="org.freedesktop.UPower" /org/freedesktop/UPower org.freedesktop.UPower.Suspend
            ;;
        Hibernate)
            dbus-send --system --print-reply --dest="org.freedesktop.UPower" /org/freedesktop/UPower org.freedesktop.UPower.Hibernate
            ;;
        LockScreen)
            dbus-send --print-reply --system --dest=org.freedesktop.DisplayManager /org/freedesktop/DisplayManager/Seat0 org.freedesktop.DisplayManager.Seat.Lock
            ;;
        Logout)
            openbox --exit
            ;;
    esac
fi
